# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Prometheus Pushgateway
# https://github.com/prometheus/pushgateway
#
scrape_configs:
  - job_name: 'pushgateway'
    dns_sd_configs:
      - names:
          - tasks.pushgateway.svc.cluster.local
        type: A
        port: 9091
        refresh_interval: "30s"
    honor_labels: true
