# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
# Scrape config for Docker Swarm Nodes
# 
# The Docker Engine metrics are required to be configured in the daemon.json file for Prometheus to scrape them.
# This configuration also includes a job to scrape the Node Exporter metrics that run on each node.
scrape_configs:
  - job_name: 'promstack/nodes/alertmanager'

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes

    relabel_configs:
      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_id
        target_label: __address__
        replacement: alertmanager.$1.cluster.local:9093

      # Set hostname as instance label
      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: instance
        replacement: $1:9093

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
      - action: labelmap
        regex: __meta_dockerswarm_(node_(?:id|hostname))

      # Set node_name label to node hostname
      # This is useful for providing compatibility with the swarmprom dashboards
      - source_labels:
          - __meta_dockerswarm_node_hostname
        target_label: node_name
