# yaml-language-server: $schema=https://json.schemastore.org/prometheus.json
#
scrape_configs:

  - job_name: 'dockerswarm/nodes/cadvisor'

    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes

    relabel_configs:
      # ================================================================================
      # Override prometheus internal labels
      # ================================================================================
      - source_labels:
        - __meta_dockerswarm_node_id
        target_label: __address__
        replacement: cadvisor.$1.cluster.local:8080

      - source_labels:
        - __meta_dockerswarm_node_address
        target_label: instance
        replacement: $1:8080

      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: __meta_(dockerswarm_node_.+)
      - action: labelmap
        regex: __meta_dockerswarm_(node_(?:id|hostname))

    metric_relabel_configs:
      # ================================================================================
      # Label mapping
      # ================================================================================
      - action: labelmap
        regex: container_label_com_(docker_.*)

      # Rename labels docker_swarm_(.+) to dockerswarm_$1
      # This is useful for compatibility with "dockerswarm-tasks.yml" relabeling
      - action: labelmap
        regex: container_label_com_docker_swarm_(.+)
        replacement: dockerswarm_$1
      - action: labeldrop
        regex: (^docker_swarm_.+)

      # ================================================================================
      # Docker Swarm compatible relabeling
      # - dockerswarm_task_name
      # ================================================================================

      # Set "task" label to "<service_name>.<task_slot>
      - source_labels:
        - dockerswarm_task_name
        target_label: task
        regex: (.+)\.(.+)\.(.+)
        replacement: $1.$2

      # ================================================================================
      # Kubernetes compatible relabeling
      # - namespace
      # - deployment
      # - pod
      # ================================================================================
      # # Set Kubernetes's Namespace with "com.docker.stack.namespace" label
      - source_labels:
        - container_label_com_docker_stack_namespace
        target_label: namespace

      # Set Kubernetes's Deployment with "com.docker.stack.namespace" label
      - source_labels:
        - container_label_com_docker_swarm_service_name
        target_label: deployment

      # Set Kubernetes's Pod Name with Docker Swarm's Service Name
      - source_labels:
        - dockerswarm_task_name
        target_label: pod
        regex: (.*)
